# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11d57727aa1b9512b7254c68e15673afc2b46fbb6e767373daecfdf85fbc0dcceadcd23b36c45aee371d4630f805297a6a7850fc651a484720ef21ea5c4660ff

test:
  secret_key_base: f86c99169c2208f409054940c82624a48ce4368302f394a39c36e3c4474c402d97750a1b08d3e10bfcc4d3f07dd1ef7fa1b2ea67dac86d9bee9e4fa082fe4de6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
